# This is a config for E2B sandbox template.
# You can use template ID (92ecr55tpt50nd0kkg2j) or template name (promptui) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("promptui") # Sync sandbox
# sandbox = await AsyncSandbox.create("promptui") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('promptui')

team_id = "ce4791a3-5dbc-43c8-81b6-196e5cc075d3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "promptui"
template_id = "92ecr55tpt50nd0kkg2j"
